let vm = new Vue({
      el: '#app',
      data: {
        dataSource: {},
        hasWindow: '',
        nearRoad: '',
        towardSouth: '',
        smokeLess: '',
        quiteness: ''
      },
      computed: {},
      methods: {},
      mounted() {
        let data = {
          "page": null,
          "respCode": 200,
          "respData": [{
              "bussId": "0609600000120170914",
              "checkinStatus": 0,
              "gmtCreate": "2019-11-13 10:55:00",
              "gmtModified": "2019-12-05 14:44:56",
              "id": 78,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 1,
              "roomFloorName": "",
              "roomImages": "group1/M00/02/55/wKjkqV3LcD2ACpVPAACAA3cgrmE777.jpg",
              "roomNo": "A1001",
              "roomStatus": 2,
              "roomToward": "朝南",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "9-1001",
              "telOutside": "83241111",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 1,
              "gmtCreate": "2019-11-13 11:24:12",
              "gmtModified": "2019-12-03 15:08:09",
              "id": 110,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 4,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "A5001",
              "roomStatus": 4,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8802",
              "telOutside": "8324111-8802",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 1,
              "gmtCreate": "2019-11-13 11:24:12",
              "gmtModified": "2019-12-03 14:51:11",
              "id": 111,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 4,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "A5002",
              "roomStatus": 1,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8803",
              "telOutside": "8324111-8803",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 1,
              "gmtCreate": "2019-11-13 11:24:12",
              "gmtModified": "2019-12-03 18:25:13",
              "id": 112,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 4,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "A5003",
              "roomStatus": 4,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8804",
              "telOutside": "8324111-8804",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 1,
              "gmtCreate": "2019-11-13 11:24:12",
              "gmtModified": "2019-12-03 17:35:16",
              "id": 113,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 4,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "A5004",
              "roomStatus": 4,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8805",
              "telOutside": "8324111-8805",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 1,
              "gmtCreate": "2019-11-13 11:24:12",
              "gmtModified": "2019-12-02 18:15:16",
              "id": 114,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 4,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "A5005",
              "roomStatus": 4,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8806",
              "telOutside": "8324111-8806",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 1,
              "gmtCreate": "2019-11-13 11:24:27",
              "gmtModified": "2019-12-04 20:19:20",
              "id": 115,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 4,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "A5006",
              "roomStatus": 2,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8802",
              "telOutside": "8324111-8802",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 0,
              "gmtCreate": "2019-11-13 11:24:27",
              "gmtModified": "2019-11-30 10:07:19",
              "id": 116,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 4,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "A5007",
              "roomStatus": 1,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8803",
              "telOutside": "8324111-8803",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 0,
              "gmtCreate": "2019-11-13 11:24:27",
              "gmtModified": "2019-11-30 10:07:19",
              "id": 118,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 4,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "A5009",
              "roomStatus": 1,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8805",
              "telOutside": "8324111-8805",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 1,
              "gmtCreate": "2019-11-13 11:24:27",
              "gmtModified": "2019-12-05 16:24:53",
              "id": 119,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 1,
              "roomBuildName": "",
              "roomFloorId": 4,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "A5010",
              "roomStatus": 4,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8806",
              "telOutside": "8324111-8806",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 0,
              "gmtCreate": "2019-11-13 11:26:48",
              "gmtModified": "2019-11-30 10:07:19",
              "id": 120,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 2,
              "roomBuildName": "",
              "roomFloorId": 5,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "B1001",
              "roomStatus": 1,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8802",
              "telOutside": "8324111-8802",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 0,
              "gmtCreate": "2019-11-13 11:26:48",
              "gmtModified": "2019-11-30 10:07:19",
              "id": 122,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 2,
              "roomBuildName": "",
              "roomFloorId": 5,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "B1003",
              "roomStatus": 1,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8804",
              "telOutside": "8324111-8804",
              "window": 1
            },
            {
              "bussId": "0609600000120170914",
              "checkinStatus": 0,
              "gmtCreate": "2019-11-13 11:26:48",
              "gmtModified": "2019-11-30 10:07:19",
              "id": 124,
              "isActive": 1,
              "isable": 1,
              "lockRoomStatus": 0,
              "nearRoad": 1,
              "picUrl": "",
              "quiet": 1,
              "roomBuildId": 2,
              "roomBuildName": "",
              "roomFloorId": 5,
              "roomFloorName": "",
              "roomImages": "",
              "roomNo": "B1005",
              "roomStatus": 1,
              "roomToward": "朝东",
              "roomTypeId": 1,
              "roomTypeName": "",
              "shopId": "",
              "smokeless": 1,
              "telInside": "8-8806",
              "telOutside": "8324111-8806",
              "window": 1
            }
          ],
          "respMsg": "成功",
          "success": true,
          "total": 13
        }

        this.dataSource = data.respData;

      }
    })